language: python

python:
    - 2.7
    - 3.3
    - 3.4

env:
    - BOKEH_DEFAULT_NO_DEV=false
    - BOKEH_DEFAULT_NO_DEV=true

matrix:
    exclude:
        - python: 3.3
          env: BOKEH_DEFAULT_NO_DEV=true
        - python: 3.4
          env: BOKEH_DEFAULT_NO_DEV=true
    allow_failures:
        - python: 3.4

before_install:
    - export PATH="$HOME/miniconda/bin:$PATH"
    - export MINICONDA_VERSION="3.5.5"
    - export PHANTOMJS_VERSION="1.9.7"

install:
    - scripts/travis_install

script:
    - nosetests --with-coverage --cover-package=bokeh && ( cd sphinx; make all; cd .. )

after_script:
    - if [[ -e examples.log ]]; then cat examples.log; fi

notifications:
    flowdock:
        secure: "ZisceYtV2b7LWNUz0wEtiR9TRk+i8x5m/N6+Htn4IFr+bBcBi79ESO0u6DWiJA5rHt+Yq7Yf49vl7UO9HZCF+8n5B1nKpfivJKngVuMYLnhYifNmwCD7vQ8aaF9DTfOqvm2hJrHwtieX8BUGs2KWd8igt3f8LCXVWVBBvkqc2L0="
